[package]
name = "low-battery-notification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnotify="1.0.3"
battery="0.7.8"
yaml-rust = "0.4"
